export const TRADE_SKILLS = [
  'Auto Mechanic',
  'Bricklaying',
  'Carpentry',
  'Cleaning',
  'Cook/Chef',
  'Dish Installation',
  'Driving',
  'Electrical works',
  'HVAC Repair',
  'Landscaping',
  'Masonry',
  'Painting',
  'Pest Control',
  'Plumbing',
  'Roofing',
  'Tiling',
  'Welding',
];
